<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Laptop Pro 15"',
                'code' => 'LP001',
                'barcode' => '1234567890123',
                'description' => 'High-performance laptop with 16GB RAM and 512GB SSD',
                'price' => 999.99,
                'cost' => 750.00,
                'stock_quantity' => 15,
                'min_stock' => 5,
                'category' => 'electronics',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'Wireless Mouse',
                'code' => 'WM001',
                'barcode' => '1234567890124',
                'description' => 'Ergonomic wireless mouse with long battery life',
                'price' => 29.99,
                'cost' => 15.00,
                'stock_quantity' => 50,
                'min_stock' => 10,
                'category' => 'electronics',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'USB-C Cable',
                'code' => 'UC001',
                'barcode' => '1234567890125',
                'description' => 'High-speed USB-C charging cable',
                'price' => 12.99,
                'cost' => 5.00,
                'stock_quantity' => 100,
                'min_stock' => 20,
                'category' => 'electronics',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'Cotton T-Shirt',
                'code' => 'TS001',
                'barcode' => '1234567890126',
                'description' => 'Comfortable 100% cotton t-shirt',
                'price' => 19.99,
                'cost' => 8.00,
                'stock_quantity' => 100,
                'min_stock' => 25,
                'category' => 'clothing',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'Denim Jeans',
                'code' => 'JN001',
                'barcode' => '1234567890127',
                'description' => 'Classic fit denim jeans',
                'price' => 49.99,
                'cost' => 25.00,
                'stock_quantity' => 75,
                'min_stock' => 15,
                'category' => 'clothing',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'Coffee Beans',
                'code' => 'CF001',
                'barcode' => '1234567890128',
                'description' => 'Premium arabica coffee beans 1kg',
                'price' => 24.99,
                'cost' => 12.00,
                'stock_quantity' => 200,
                'min_stock' => 50,
                'category' => 'food',
                'unit' => 'kg',
                'tax_rate' => 5.00,
                'is_active' => true,
            ],
            [
                'name' => 'Fresh Bread',
                'code' => 'FB001',
                'barcode' => '1234567890129',
                'description' => 'Freshly baked whole wheat bread',
                'price' => 3.99,
                'cost' => 1.50,
                'stock_quantity' => 30,
                'min_stock' => 10,
                'category' => 'food',
                'unit' => 'pcs',
                'tax_rate' => 5.00,
                'is_active' => true,
            ],
            [
                'name' => 'Bottled Water',
                'code' => 'BW001',
                'barcode' => '1234567890130',
                'description' => 'Mineral water 500ml bottle',
                'price' => 1.99,
                'cost' => 0.50,
                'stock_quantity' => 500,
                'min_stock' => 100,
                'category' => 'food',
                'unit' => 'pcs',
                'tax_rate' => 5.00,
                'is_active' => true,
            ],
            [
                'name' => 'Office Chair',
                'code' => 'OC001',
                'barcode' => '1234567890131',
                'description' => 'Ergonomic office chair with lumbar support',
                'price' => 199.99,
                'cost' => 120.00,
                'stock_quantity' => 20,
                'min_stock' => 5,
                'category' => 'furniture',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
            [
                'name' => 'Desk Lamp',
                'code' => 'DL001',
                'barcode' => '1234567890132',
                'description' => 'LED desk lamp with adjustable brightness',
                'price' => 34.99,
                'cost' => 18.00,
                'stock_quantity' => 40,
                'min_stock' => 8,
                'category' => 'furniture',
                'unit' => 'pcs',
                'tax_rate' => 10.00,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
